Repository laminas-api-tools/api-tools-documentation, pull requests merged in 2021-06, with the labels that each got.

#23 WIP: Add support for PHP 8
  composer.json
  composer.lock
  src/ApiFactory.php
  src/Module.php
Labels: Enhancement

#18 Qa/psalm
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml.dist
  src/Api.php
  src/ApiFactory.php
  src/Field.php
  src/Operation.php
  src/Service.php
  test/ApiFactoryTest.php
  test/ControllerFactoryTest.php
  test/ControllerTest.php
Labels: Enhancement, hacktoberfest-accepted

#24 Missing php 8 in composer.json
  composer.json
  composer.lock
Labels: Bug
